import os

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch


def create_pdf(title, content):

    folder = "media/generated_pdf"

    os.makedirs(folder, exist_ok=True)

    file_path = os.path.join(
        folder,
        "study_notes.pdf"
    )

    doc = SimpleDocTemplate(
        file_path,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER

    body_style = styles["BodyText"]
    body_style.leading = 20

    footer_style = styles["Italic"]
    footer_style.alignment = TA_CENTER

    story = []

    # Title
    story.append(
        Paragraph(title, title_style)
    )

    story.append(
        Spacer(1, 0.3 * inch)
    )

    # Content
    story.append(
        Paragraph(
            content.replace("\n", "<br/>"),
            body_style,
        )
    )

    story.append(
        Spacer(1, 0.5 * inch)
    )

    # Footer
    story.append(
        Paragraph(
            "<b>Generated by Vetri AI Study Buddy</b>",
            footer_style,
        )
    )

    doc.build(story)

    return file_path