# Generated by Django 6.0.7 on 2026-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('feature', models.CharField(choices=[('Notes', 'Notes'), ('Quiz', 'Quiz'), ('Flashcards', 'Flashcards'), ('Study Plan', 'Study Plan')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
