# Generated by Django 6.0.7 on 2026-07-15 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0002_aihistory_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aihistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI History', 'verbose_name_plural': 'AI Histories'},
        ),
        migrations.AlterField(
            model_name='aihistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
